### ISSUE TITLE
Update to Guzzle 6

### ISSUE THREAD

**Issue by SchumacherFM** [detailnet/denner-client#30]
Hi there,

do you consider updating to Guzzle 6? 

Because many other different packages are already on Guzzle 6 and your package with Guzzle 5 will break a composer setup ...

Let me know.

Thanks

**Comment by ivan-wolf** [comment]
Thank you, @SchumacherFM, for the request and sorry for getting back to you so late.

Are you still in need of the upgrade to Guzzle 6?
We could make that happen.

**Comment by SchumacherFM** [comment]
Hi Ivan,

would be nice to have!
